package com.example.a103.datasearch.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a103.datasearch.data.Tool;
import com.example.a103.datasearch.data.CoefficientParameters;
import com.example.a103.datasearch.data.MaterialCuttingLimits;
import com.example.a103.datasearch.data.Material;
import com.example.a103.datasearch.data.MaterialCategories;

import com.example.a103.datasearch.dao.ToolDao;
import com.example.a103.datasearch.dao.CoefficientParametersDao;
import com.example.a103.datasearch.dao.MaterialCuttingLimitsDao;
import com.example.a103.datasearch.dao.MaterialDao;
import com.example.a103.datasearch.dao.MaterialCategoriesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig toolDaoConfig;
    private final DaoConfig coefficientParametersDaoConfig;
    private final DaoConfig materialCuttingLimitsDaoConfig;
    private final DaoConfig materialDaoConfig;
    private final DaoConfig materialCategoriesDaoConfig;

    private final ToolDao toolDao;
    private final CoefficientParametersDao coefficientParametersDao;
    private final MaterialCuttingLimitsDao materialCuttingLimitsDao;
    private final MaterialDao materialDao;
    private final MaterialCategoriesDao materialCategoriesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        toolDaoConfig = daoConfigMap.get(ToolDao.class).clone();
        toolDaoConfig.initIdentityScope(type);

        coefficientParametersDaoConfig = daoConfigMap.get(CoefficientParametersDao.class).clone();
        coefficientParametersDaoConfig.initIdentityScope(type);

        materialCuttingLimitsDaoConfig = daoConfigMap.get(MaterialCuttingLimitsDao.class).clone();
        materialCuttingLimitsDaoConfig.initIdentityScope(type);

        materialDaoConfig = daoConfigMap.get(MaterialDao.class).clone();
        materialDaoConfig.initIdentityScope(type);

        materialCategoriesDaoConfig = daoConfigMap.get(MaterialCategoriesDao.class).clone();
        materialCategoriesDaoConfig.initIdentityScope(type);

        toolDao = new ToolDao(toolDaoConfig, this);
        coefficientParametersDao = new CoefficientParametersDao(coefficientParametersDaoConfig, this);
        materialCuttingLimitsDao = new MaterialCuttingLimitsDao(materialCuttingLimitsDaoConfig, this);
        materialDao = new MaterialDao(materialDaoConfig, this);
        materialCategoriesDao = new MaterialCategoriesDao(materialCategoriesDaoConfig, this);

        registerDao(Tool.class, toolDao);
        registerDao(CoefficientParameters.class, coefficientParametersDao);
        registerDao(MaterialCuttingLimits.class, materialCuttingLimitsDao);
        registerDao(Material.class, materialDao);
        registerDao(MaterialCategories.class, materialCategoriesDao);
    }
    
    public void clear() {
        toolDaoConfig.clearIdentityScope();
        coefficientParametersDaoConfig.clearIdentityScope();
        materialCuttingLimitsDaoConfig.clearIdentityScope();
        materialDaoConfig.clearIdentityScope();
        materialCategoriesDaoConfig.clearIdentityScope();
    }

    public ToolDao getToolDao() {
        return toolDao;
    }

    public CoefficientParametersDao getCoefficientParametersDao() {
        return coefficientParametersDao;
    }

    public MaterialCuttingLimitsDao getMaterialCuttingLimitsDao() {
        return materialCuttingLimitsDao;
    }

    public MaterialDao getMaterialDao() {
        return materialDao;
    }

    public MaterialCategoriesDao getMaterialCategoriesDao() {
        return materialCategoriesDao;
    }

}
