package com.example.a103.datasearch.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a103.datasearch.data.Tool;

import com.example.a103.datasearch.dao.ToolDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig toolDaoConfig;

    private final ToolDao toolDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        toolDaoConfig = daoConfigMap.get(ToolDao.class).clone();
        toolDaoConfig.initIdentityScope(type);

        toolDao = new ToolDao(toolDaoConfig, this);

        registerDao(Tool.class, toolDao);
    }
    
    public void clear() {
        toolDaoConfig.clearIdentityScope();
    }

    public ToolDao getToolDao() {
        return toolDao;
    }

}
